name: Minimal Error Debugging

on:
    workflow_dispatch: # 수동으로 실행할 수 있도록 설정

jobs:
    debug:
        runs-on: ubuntu-latest

        steps:
            - name: Debug and Multi-line Output Test
              run: |
                  # 쉘 디버깅 옵션 활성화: 각 명령어 실행 전 출력, 에러 발생 시 즉시 중단
                  set -euxo pipefail

                  echo "### 간단한 메시지 출력 ###"
                  echo "Hello, world!"

                  # GITHUB_OUTPUT 파일에 멀티라인 출력값을 설정합니다.
                  # 아래 구문은 output key 'multi_line_output'에 여러 줄의 값을 기록합니다.
                  echo "multi_line_output<<DEBUG_DELIM" >> $GITHUB_OUTPUT
                  echo "Line 1: Debugging started." >> $GITHUB_OUTPUT
                  echo "Line 2: Detailed log information." >> $GITHUB_OUTPUT
                  echo "DEBUG_DELIM" >> $GITHUB_OUTPUT

                  echo "### 의도적으로 에러 발생 ###"
                  # 존재하지 않는 디렉토리를 나열하여 에러를 발생시켜 디버깅 로그를 확인합니다.
                  ls non_existent_directory
