name: Test Trigger

on:
    push:
        branches:
            - feature/haechan/init-github-action

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v3
            - name: Echo something
              run: echo "✅ 워크플로우 실행 성공"
